name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: netstandard2.1
    - name: Restore dependencies
      run: dotnet restore ./Moduler.Helpers.sln
    - name: Build
      run: dotnet build Moduler.Helpers/Moduler.Helpers.csproj --configuration Release --no-restore
    - name: Pack
      run: dotnet pack src/Moduler.Helpers/Moduler.Helpers.csproj --configuration Release --no-build --output ./bin/Release
    - name: NuGet Push
      run: dotnet nuget push "./bin/Release/*.nupkg" --source "github" --skip-duplicate
      working-directory: src/Moduler.Helpers
