name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Moduler.Helpers/Moduler.Helpers.csproj
      working-directory: /home/runner/work/helpers/helpers
    - name: Build
      run: dotnet build Moduler.Helpers/Moduler.Helpers.csproj --configuration Release --no-restore
      working-directory: /home/runner/work/helpers/helpers
    - name: Test
      run: dotnet test Moduler.Helpers/Moduler.Helpers.csproj --no-build --verbosity normal
      working-directory: /home/runner/work/helpers/helpers
    - name: Pack
      run: dotnet pack Moduler.Helpers/Moduler.Helpers.csproj --configuration Release --no-build --output ./bin/Release
      working-directory: /home/runner/work/helpers/helpers
    - name: NuGet Push
      run: dotnet nuget push "./bin/Release/*.nupkg" --source "github" --skip-duplicate
      working-directory: /home/runner/work/helpers/helpers
