name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: netstandard2.1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build "Moduler.Helper.csproj" --configuration Release --no-restore
    - name: Test
      run: dotnet test "Moduler.Helper.csproj" --no-build --verbosity normal
    - name: Pack
      run: dotnet pack "Moduler.Helper.csproj" --configuration Release --no-build --output ./bin/Release
    - name: NuGet Push
      run: dotnet nuget push "./bin/Release/*.nupkg" --source "github" --skip-duplicate
